CREATE TABLE events (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(255) NOT NULL,
start_of_event TIMESTAMP NOT NULL,
duration INTEGER,
date_of_creation TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
description TEXT,
status VARCHAR(255) NOT NULL,
location VARCHAR(255)
);