services:
  # MySQL
  mysql-server:
    env_file:
      - ../event-api.env
    image: mysql:8.0
    volumes:
      - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    ports:
      - "3308:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 15s

  # event-api
  event-api:
    env_file:
      - ../event-api.env
    image: event-api:latest
    build: ../.
    ports:
      - "8080:8080"
    depends_on:
      mysql-server:
        condition: service_healthy